### ISSUE TITLE
ClickThrough to containers only works with vanilla chests/barrels

### ISSUE THREAD

**Issue by Liangv2024** [cassiancc/ClickThrough-Infinite#2]
Hello, this mod only supports the original container and does not work on other mod containers. Is there any solution?
My English is not very good, please forgive me!

**Comment by Deses** [comment]
+1 on this. Support for Expanded Storage would be good.

**Comment by Deses** [comment]
+1 on this @cassiancc. Support for Expanded Storage would be good, or just an array where we can define what blocks can be clicked through.

**Comment by cassiancc** [comment]
I will work on this. In the meantime, you can disable the "Only click through to containers" setting, and it will click through to all blocks.

**Comment by Deses** [comment]
Oh, neat! "Only click through to containers" does what I wanted so I just didn't understand the setting just by the name alone. 😂
Surely it will have some unintended consequences, though.

**Comment by cassiancc** [comment]
It'll click through to normal blocks, yes, but that was the behaviour of the original mod. Consider it a temporary workaround while I work on the fix. Should be able to release it tonight.

**Comment by cassiancc** [comment]
Fixed in 3.2.

**Comment by Liangv2024** [comment]
> 在3.2中修复。

thank you
